name: Run NPM Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install and lerna bootstrap
        run: |
          npm install -g npm@latest
          npm install silent
          npm run bootstrap
      - name: Run tests
        run: npm run test
